# Comment to a new issue.
pullRequestOpened: |
  Thank you for raising your pull request.
  
  To ensure that all licensing criteria is met all repositories of the LVGL project apply a process called DCO (Developer's Certificate of Origin). 
  
  The text of DCO can be read here: https://developercertificate.org/
  
  By contributing to any repositories of the LVGL project you state that your contribution corresponds with the DCO.
  
  No further action is required if your contribution fulfills the DCO. If you are not sure about it feel free to ask us in a comemnt. 
