blank_issues_enabled: false
contact_links:
  - name: CONTIBUTING.md
    url: https://github.com/lvgl/lvgl/blob/master/docs/CONTRIBUTING.md#faq-about-contributing
    about: The basic rules of contributing
  - name: CODING_STYLE.md
    url: https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md
    about: Quick summary of LVGL's code style
